"""ais positions keyed by vessel identifier

Revision ID: 1d2e91e4f01f
Revises: b2c7f1a90d31
Created: 2026-09-16 20:44:06.509762
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1d2e91e4f01f'
down_revision = 'b2c7f1a90d31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ais_positions', sa.Column('vessel_id', sa.String(length=64), nullable=False))
    op.alter_column('ais_positions', 'mmsi',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_ais_mmsi_t'), table_name='ais_positions')
    op.create_index(op.f('ix_ais_positions_vessel_id'), 'ais_positions', ['vessel_id'], unique=False)
    op.create_index('ix_ais_vessel_t', 'ais_positions', ['vessel_id', 't'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ais_vessel_t', table_name='ais_positions')
    op.drop_index(op.f('ix_ais_positions_vessel_id'), table_name='ais_positions')
    op.create_index(op.f('ix_ais_mmsi_t'), 'ais_positions', ['mmsi', 't'], unique=False)
    op.alter_column('ais_positions', 'mmsi',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('ais_positions', 'vessel_id')
    # ### end Alembic commands ###
